# Generated by Django 3.1.6 on 2021-05-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('date', models.DateField()),
            ],
        ),
    ]
